language: java
before_install:
# set vars
- export TESTS_PATH=src/tests
- export DEPENDENCIES=dependencies
- export ENVIRONMENT=$DEPENDENCIES
- export GOAL_RUNTIME=$DEPENDENCIES/runtime-2.0.2-SNAPSHOT-jar-with-dependencies.jar
- export GOAL_SETTINGS=$DEPENDENCIES/settings.yaml
- export GOAL_COMMAND=goal.tools.eclipse.RunTool

install:
#login into connector
- java -cp $ENVIRONMENT/contextvh-*-jar-with-dependencies.jar login.Login $TYGRON_USER $TYGRON_PASS

before_script:
#see all test files and move them
- for f in $TESTS_PATH/*.test2g; do echo "$f"; done
script:
#test the files
- for filename in $TESTS_PATH/*.test2g; do echo "$filename"; timeout 99 java -cp $GOAL_RUNTIME $GOAL_COMMAND $GOAL_SETTINGS $filename > $(basename $filename).txt || echo "Test output hidden to reduce travis log size"; done

- ls
- if grep -Fq "test failed" *.txt; then echo "FAILURE HAPPENED"; $?; else echo "No test failed."; fi
- for testfile in *.txt; do if grep -Fq "test passed" $testfile; then echo "$testfile passed..."; else echo "$testfile failed"; $?; fi; done;
jdk:
- oraclejdk8